# Generated by Django 4.0.4 on 2022-04-25 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogistic_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id_service', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id_worker', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=30)),
                ('position', models.CharField(default='Грузчик', max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id_operator', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=30)),
                ('position', models.CharField(default='Оператор', max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
