# Generated by Django 4.0.4 on 2022-07-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogistic_backend', '0003_alter_client_user_alter_operator_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id_order', models.IntegerField(primary_key=True, serialize=False)),
                ('addressPV', models.CharField(max_length=100)),
                ('addressPD', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('time_in', models.TimeField(null=True)),
                ('count_objects', models.IntegerField()),
                ('weight', models.FloatField()),
                ('type_thing', models.CharField(max_length=100)),
                ('confirmation_order', models.CharField(default='Подтвержденно', max_length=20)),
                ('price', models.IntegerField()),
                ('type_pay', models.CharField(choices=[('card', 'Картой'), ('cash', 'Наличные')], max_length=100)),
                ('status_order', models.CharField(choices=[('В обработке', 'В обработке'), ('В процессе', 'В процессе'), ('Закончен', 'Закончен')], default='В обработке', max_length=100)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogistic_backend.client')),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogistic_backend.operator')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogistic_backend.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.IntegerField(primary_key=True, serialize=False)),
                ('type_car', models.CharField(choices=[('small', 'Малый от 500 кг до 2 тонн'), ('medium', 'Средний от 2 тонн до 5 тонн'), ('big', 'Большой от 5 тонн до 16 тонн'), ('very_big', 'Сверхтяжелый от 16 тонн и выше')], max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogistic_backend.worker')),
            ],
        ),
    ]
