# Generated by Django 4.0.4 on 2022-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogistic_backend', '0005_car_order_additional_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Card_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
