# Generated by Django 4.0.4 on 2022-09-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogistic_backend', '0006_alter_client_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Card_number',
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='series_number_passport',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='series_number_passport',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='series_number_passport',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
