# Generated by Django 4.0.4 on 2022-09-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogistic_backend', '0007_remove_client_card_number_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
