# Generated by Django 4.0.4 on 2022-09-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogistic_backend', '0010_alter_car_price_alter_car_type_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='free', max_length=20, null=True),
        ),
    ]
