# Generated by Django 4.0.4 on 2022-10-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogistic_backend', '0011_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogistic_backend.worker'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogistic_backend.operator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogistic_backend.worker'),
        ),
    ]
