# Generated by Django 4.0.4 on 2022-10-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogistic_backend', '0012_alter_car_id_worker_alter_order_id_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_pay',
            field=models.CharField(default='Не оплачено', max_length=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='id_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogistic_backend.worker'),
        ),
        migrations.AlterField(
            model_name='car_order',
            name='number_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogistic_backend.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Водитель выехал к начальному адрессу', 'Водитель выехал к начальному адрессу'), ('Водитель приехал к начальному адрессу', 'Водитель приехал к начальному адрессу'), ('Водитель выехал к конечному адрессу', 'Водитель выехал к конечному адрессу'), ('Водитель приехал к конечному адрессу', 'Водитель приехал к конечному адрессу'), ('Заказ завершен', 'Заказ завершен')], default='В обработке', max_length=100),
        ),
    ]
